### ISSUE TITLE
Proposition for unique transfer ID

### ISSUE THREAD

**Issue by marakiis** [waarp/Waarp-All#102]
Given two partners exchanging transfers if one of the transfer IDs is reset (DB purge, ...) new transfers cannot be added as the partners who did not reset its IDs  will refuse with the reason the TransferID already exists for the given  owner/requester/requested.

A solution would be to use unix epoch in nanoseconds for transfer IDs (instead of DB increments) , this would ensure uniqueness of IDs given a unique partners does not overload with transfers. The IDs would have a expiration date in year 2554 which should be a comfortable margin.

**Comment by fredericBregier** [comment]
I understand the concern.
Sadly, even giving nanoseconds does not prevent to have 2 same ids:
- one server can assign, due to parallism of threads, 2 times (or more) the same id using nano (easy to demonstrate)
- two servers, concurrently acting with various partner, but most of all between each other for 2 different transfers (such that conflict can occur) could lead to the very same id again
Using time (even nano) is not a good idea in general, considering parallelism, both local and distant. That's why generally we used GUID (Global Unique Id) which are partly set from time, local information and local counter.

So the reason in Waarp we have somme different implementation of GUUID (WaarpCommon): 
- LongUuid (based on PID, timestamp, limited to 6 bytes) which is already used by:
  - FollowId: https://github.com/waarp/Waarp-All/blob/cc65fc49915670412d48a2de5f452e393163d6cc/WaarpR66/src/main/java/org/waarp/openr66/client/TransferArgs.java#L575
  - and partially in case of no Database for SpecialIdl: https://github.com/waarp/Waarp-All/blob/cc65fc49915670412d48a2de5f452e393163d6cc/WaarpR66/src/main/java/org/waarp/openr66/dao/xml/XMLTransferDAO.java#L339

Advantages:
- already a Long as before (8 bytes = 64 bits)
- clean and efficient
Disadvantages:
- not enough precise so can lead to a slowdown when getting multiple concurrent ids (due to check of unicity in synchronized block)

Another solution could be to use another GUID (not from JDK since they are known to be buggy) but as the other one in WaarpCommon (GUID) but it leads to change the representation to a 21 bytes instead of 8 bytes, which leads to ascendant incompatibility.

So we can change to LongUuid, chaning getNextId (for all databases) to new LonUuid().

WDYT?

**Comment by fredericBregier** [comment]
I can handle this in 3.6.1 (currently in work stage) if you think it is ok from your perspective.

**Comment by fredericBregier** [comment]
Correction on LongUuid implementation:
- local PID (2 bytes) (G of GUID)
- time using 3.5 bytes (from 3 to 28, so the seconds plus x/250 second, so not fully millisecond)
- counter on 2,5 bytes (2^20 = 1 Millions item) which leads to the ability to have up 1 Millions concurrent Id in the same 4 ms interval, so 260K each ms, so 1 each 4 ns, but with a synchronized block ensuring that even during those 4ns, none will have the same value (up to 1 million).

It's based on various algorithm, one of the best I found few years ago.

**Comment by fredericBregier** [comment]
I forgot: nanosecond in Java is not "real" in the sens it does not give the right time. It is only supported to measure range of time (2 nanosecond takes to make the difference).

**Comment by fredericBregier** [comment]
In the current proposition, GUID (long) is becoming the default (while still possible to come back to SQL Sequence).

I would like to change a bit the proposal:
1) Default being SQL Sequence but with a change (see below)
2) Possibility to go to GUID (long) (so not the default)

First, the new SQL Sequence could be initiate with the current timestamp (if not already existing of course), or reinitialize to this timestamp. This could help to ensure that if a database is recreated from scratch, there will be no issue since the previous ID will be in past from this timestamp.

However, since this is a sequence, it is possible on the very beginning that this sequence gives ID that are virtually in the future (let say that 1000 transfers just start at the very beginning of the restart with a fresh database, then the sequence could be about 1s in the future compared to current time). 
Then, if one re-reset again the sequence, there could be issue on the very last assigned IDs and newly created ones. 
However, this only concerns the very startup, since after it is highly improbable that those ID continues to go in the future, comparing to timestamp (it would imply to create more than 1 transfer/ms for a long period). 
As recreating the database (or resetting it) takes some time, I believe that this should not be an issue, since it will take at least 1 or 2 seconds to be done (therefore, about 2000 Ids before resetting).
So, except if a value is given for the reset (then the value must be taken as is), the timestamp used must be the "latest time as possible", such that it is as much as possible away from a possible previous reset.

This solution has the advantage to continue to have a sequence of Ids (which is not guaranteed by GUID). It allows still to have unicity (while GUID is giving such a promise, it is not 100% guaranteed but I would say about 99.999999999%). I believe GUID long implementation is far away enough and sure however, but no real sequence (even if there is a form of sequence but not humanly visible).

On the opposite, using sequence implies a SQL request (so delay and load on SQL server), while GUID is immediate (my test gives about 1Million generated GUID/s, far more than what a SQL command can do.

So it is a choice on:
1) Human readability: SQL Sequence
2) Performance: GUID

I would go, IMHO, to human readability, since performance is not that important (tests do not shown significative impact). But on highly loaded servers, that could be interesting to lose the first property to gain in performance, so to keep the option however.

WDYT?

**Comment by fredericBregier** [comment]
@marakiis Done with still SQL Sequence by default (but optimized and initialization fixed) and other options using GUID activable
