### ISSUE TITLE
Transfer listing does not load if a rule has been deleted

### ISSUE THREAD

**Issue by bcarlin** [waarp/Waarp-All#19]
In the Admin HTTPS interface, if a transfer uses a rule that has been removed, the transfer listing does not show the transfer, but an error message.

**Steps to reproduce**

- create a rule "foo"
- do a transfer with the rule "foo"
- delete the rule "foo"
- go to the admin interface and navigate to the transfer listing page

**Expected outcome**

the transfer that used the rule "foo" shows in the list of transfers

**Actual outcome**

The https interface shows this error:

    !ErrorCode.17!: Rule cannot be found for DbTaskRunner: {"@model":"DbTaskRunner","SPECIALID":-9223372036854775795,"RETRIEVEMODE":false,"IDRULE":"test","MODETRANS":1,"FILENAME":"/in/-9223372036854775795_3185345321839916308_foo.txt","ORIGINALNAME":"/out/foo.txt","FILEINFO":"noinfo","ISMOVED":false,"BLOCKSZ":65536,"OWNERREQ":"server","REQUESTER":"client","REQUESTED":"server","TRANSFERINFO":"{\"ORIGINALSIZE\":12}","GLOBALSTEP":4,"GLOBALLASTSTEP":4,"STEP":0,"STEPSTATUS":"O ","INFOSTATUS":"O ","RANK":1,"STARTTRANS":1587989702508,"STOPTRANS":1587989702609,"UPDATEDINFO":6,"ORIGINALSIZE":-1}

The logs contains only this warning :

    28/04/2020/09:58:57.783 WARN [org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler] [HttpWorker-12] org.waarp.openr66.protocol.http.adminssl.HttpResponsiveSslHandler.setDbTaskRunnerJsonData(HttpResponsiveSslHandler.java:208) : [server] OpenR66 Web Error Rule cannot be found for DbTaskRunner: {"@model":"DbTaskRunner","SPECIALID":-9223372036854775795,"RETRIEVEMODE":false,"IDRULE":"test","MODETRANS":1,"FILENAME":"/in/-9223372036854775795_3185345321839916308_foo.txt","ORIGINALNAME":"/out/foo.txt","FILEINFO":"noinfo","ISMOVED":false,"BLOCKSZ":65536,"OWNERREQ":"server","REQUESTER":"client","REQUESTED":"server","TRANSFERINFO":"{\"ORIGINALSIZE\":12}","GLOBALSTEP":4,"GLOBALLASTSTEP":4,"STEP":0,"STEPSTATUS":"O  ","INFOSTATUS":"O  ","RANK":1,"STARTTRANS":1587989702508,"STOPTRANS":1587989702609,"UPDATEDINFO":6,"ORIGINALSIZE":-1}

**Comment by fredericBregier** [comment]
Well, the first error is that a rule should not be deleted if used elsewhere.
The reason there is no "foreign key" constraint is probably because some operations are not compatible with this (as for instance reimport all rules, including first deleting every rules before creating them again).

So now on this "behaviour": the object DbTaskRunner depends on a sub object DbRule. Of course, if there is no such DbRule, then there cannot be such any dependent DbTaskRunner.

So the warn is correct:  `Rule cannot be found for DbTaskRunner`

So what we can do? IMHO, getting an output of error (as shown) and letting all other DbTaskRunner to be printed. This is what we've got.

So my question is: What should be according to you the correct behaviour ?

**Comment by bcarlin** [comment]
The transfer listing actually plays two roles:
* It shows "current" transfers (ongoing and pending transfers, short-term history)
* It is the only way to show transfer history.

For the second part, the rule may not exist. 
What also bothers me is that, AFAIK, there is no need to get rule data from the database to display the listing page.

The outcome I expect is to show the transfers without error even if the rule (or partner FWIW) does not exist.

I think the culprit is around [here](https://github.com/waarp/Waarp-All/blob/v3.3/WaarpR66/src/main/java/org/waarp/openr66/database/data/DbTaskRunner.java#L932): the rule is eager loaded, maybe the relation could be lazy-loaded.

**Comment by fredericBregier** [comment]
I understand lazy-loading, but this will break a lot of usage, where rule MUST be fully loaded to be correctly used.
Therefore, for this very specific usage, we need to create a very new constructor with no loading at all of DbRule... I will go for it.
However I feel like the case here is breaking the very standard of relational database meaning, even if constraint is not active (which is the case here, allowing thus to delete the DbRule while it is still used somewhere). So the correction will be a hack, only to display what is no more displayable since the rule is no more existing...

**Comment by bcarlin** [comment]
I understand that the code treats a runner's rule as a foreign key, even if it is not "materialized" in the database.

To express my issue another way. I'd like for both of these use cases to be possible :

> As an administrator
> I want to delete a transfer rule
> So that it cannot be used for transfers anymore

> As an operator
> I want to consult transfer history
> So that I can know what has been transferred

Presently, this is not possible, because of this error.

One way to solve this would be to lazy load the rule (my first proposal). 

If it breaks too many things, another way to do that while keeping the idea of the foreign key is to prevent the deletion of the rules (and hosts) if there are transfers that use it, optionally letting the user ask for the deletion of those transfers (the same way an RDBMS would process a "delete" and a "delete cascade" with a foreign key).

However, we need a way to disable a rule, so that it cannot be used, but without deleting it. My first use case becomes:

> As an administrator
> I want to disable a transfer rule
> So that it cannot be used for transfers anymore

The purpose is the same.

(as a sidenote, I know I I could set `<hostids><hostid>host-that-will-never-ever-exist</hostid></hostids>` to the rule to prevent its use, but it feels to hacky for me...).

What do tyou think ?

**Comment by fredericBregier** [comment]
Here is a proposal to fix #19 in #20 . The general idea is to limit this to "printing" events, and adding an extra code (red color) to missing rule.

I believe this the simplest change to have the behaviour as you specified. Note that however no action can be taken on those DbTaskRunner (stop, cancel, restart) since the Rule is missing and mandatory for such actions. But all others (listing, export, purge) are ok.

**Comment by bcarlin** [comment]
This is fine with me, except for the red color which is misleading: red is already used for transfers errors (here, it might be a success).
It seems to me that "color: gray" or "opacity: 0.4" could be more appropriate (a faded effect for archive) without being misleading.

**Comment by fredericBregier** [comment]
Red color is only on rule column, not anywhere else and only on textual part (not layout). 
So it is a different case. And as you like "standard", red is clearly indicating an issue; and there is a real issue there since Rule does not exist anymore while it should.

**Comment by bcarlin** [comment]
Ok. So since it is an error, we must not let the user delete a rule if there are runners that refer to it (if we let the user do a mistake without telling him/her it is a mistake, he/she will assume it was correct and will not understand the error).

**Comment by fredericBregier** [comment]
The last MR contains both:
- fix for printing issue
- fix for deletion command on Rule when a TaskRunner exists with this Rule referenced (this is checked within HTTPS Admin interface - Responsive or not - and in the REST interface - V1 and V2 -)

The reason we keep both is that some extra actions need to allow deletion with no control (such as full reimport of Rules which first delete all existing Rules), and therefore such a situation can still occur. However the printing (HTML) will be kept correct (with a warning).
